version: '3'
networks:
  krakend-net:
    external: true
services:

  auth-service:
    image: auth-jsapp:latest
    container_name: auth-jsapp
    ports:
      - 8084:3000
    networks:
      - krakend-net
  
  user-service:
    image: user-jsapp:latest
    container_name: user-jsapp
    ports:
      - 8081:3000
    networks:
      - krakend-net
  
  course-service:
    image:  course-jsapp:latest
    container_name:  course-jsapp
    ports:
      - 8082:3000
    networks:
      - krakend-net
  
  taken-service:
    image: taken-jsapp:latest
    container_name: taken-jsapp
    ports:
      - 8083:3000
    networks:
      - krakend-net
  
  # main-service:
  #   image: main-jsapp:latest
  #   container_name: main-jsapp
  #   ports:
  #     - 8085:80
  #   networks:
  #     - krakend-net
  
  # reserv-service:
  #   image: reserv-jsapp:latest
  #   container_name: reserv-jsapp
  #   ports:
  #     - 8086:80
  #   networks:
  #     - krakend-net

  db-appservice:
    image: postgres
    container_name: db-appservice
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tahubulat
      POSTGRES_DB: app-service
    volumes:
      - ./db-config:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - krakend-net

  # pgadmin:
  #   image: dpage/pgadmin4:latest
  #   container_name: pgadmin
  #   restart: always
  #   volumes:
  #     - pgadmin-data:/var/lib/pgadmin
  #   ports:
  #     - 5580:80
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@localhost.com
  #     PGADMIN_DEFAULT_PASSWORD: tahubulat
  #   networks:
  #     - krakend-net

# volumes:
#   # pgadmin-data:
#   db-config:
#     external: true